export const environment = {
  production: true,
  worldskillsAppId: 2700,
  worldskillsApi: 'https://api.worldskills.org',
  worldskillsApiAccreditation: 'https://api.worldskills.org/registrations/accreditation',
  worldskillsApiImages: 'https://api.worldskills.org/images',
  worldskillsApiOrg: 'https://api.worldskills.org/org',
  worldskillsApiPeople: 'https://api.worldskills.org/people',
  worldskillsApiLogs: 'https://api.worldskills.org/logs',
  worldskillsAccreditation: 'https://accreditation.worldskills.org',
  worldskillsPeople: 'https://people.worldskills.org',
  worldskillsClientId: 'a95703d1aa96',
  worldskillsAuthorizeUrl: 'https://auth.worldskills.org/oauth/authorize',
  worldskillsAuthorizeRedirect: 'https://accreditation.worldskills.org/',
  worldskillsAuthorizeUserinfoEndpoint: 'https://auth.worldskills.org/auth/users/loggedIn',
  worldskillsPuppeteer: 'https://api.worldskills.org/auth/sessions/operate_puppet',
  worldskillsAuthUriPatterns: ['api.worldskills.org'],
  environmentWarning: "",
  appRoles: {
    ADMIN: 'Admin',
    EDIT: 'AccreditationEdit',
    UPLOAD_PHOTO: 'AccreditationUploadPhoto',
    EDIT_DELEGATE_TYPES: 'AccreditationEditDelegateTypes',
    EDIT_POSITIONS: 'AccreditationEditPositions',
    EDIT_ZONES: 'AccreditationEditZones',
    EDIT_PACKAGE_OPTIONS: 'AccreditationEditPackageOptions',
    PRINT: 'AccreditationPrint',
    AD_HOC_PRINT: 'AccreditationAdHocPrint',
    SET_UP_SCAN_APP: 'AccreditationSetUpScanApp',
    VIEW_SCANS: 'AccreditationViewScans',
    REQUEST_ZONE: 'AccreditationRequestZone',
    ALLOCATE_ZONE_REQUEST: 'AccreditationAllocateZoneRequest',
    VERIFY_ALLOCATION: 'AccreditationVerifyAllocation',
    VIEW_ACCREDITATIONS: 'AccreditationViewAccreditations',
  }
};
