export const environment = {
  production: false,
  worldskillsAppId: 2700,
  worldskillsApi: 'http://localhost:8080',
  worldskillsApiAccreditation: 'http://localhost:8080/registrations/accreditation',
  worldskillsApiImages: 'http://localhost:8080/images',
  worldskillsApiOrg: 'http://localhost:8080/org',
  worldskillsApiPeople: 'http://localhost:8080/people',
  worldskillsApiLogs: 'http://localhost:8080/logs',
  worldskillsAccreditation: 'http://localhost:4200/',
  worldskillsPeople: 'https://people.worldskills.org',
  worldskillsClientId: 'a95703d1aa96',
  worldskillsAuthorizeUrl: 'http://localhost:50300/oauth/authorize',
  worldskillsAuthorizeRedirect: 'http://localhost:12100/',
  worldskillsAuthorizeUserinfoEndpoint: 'http://localhost:50300/auth/users/loggedIn',
  worldskillsPuppeteer: 'https://api.worldskills.show/auth/sessions/operate_puppet',
  worldskillsAuthUriPatterns: ['localhost:8080'],
  environmentWarning: 'This is the local (full) development environment. Happy coding!',
  appRoles: {
    ADMIN: 'Admin',
    EDIT: 'AccreditationEdit',
    UPLOAD_PHOTO: 'AccreditationUploadPhoto',
    EDIT_DELEGATE_TYPES: 'AccreditationEditDelegateTypes',
    EDIT_POSITIONS: 'AccreditationEditPositions',
    EDIT_ZONES: 'AccreditationEditZones',
    EDIT_PACKAGE_OPTIONS: 'AccreditationEditPackageOptions',
    PRINT: 'AccreditationPrint',
    AD_HOC_PRINT: 'AccreditationAdHocPrint',
    SET_UP_SCAN_APP: 'AccreditationSetUpScanApp',
    VIEW_SCANS: 'AccreditationViewScans',
    REQUEST_ZONE: 'AccreditationRequestZone',
    ALLOCATE_ZONE_REQUEST: 'AccreditationAllocateZoneRequest',
    VERIFY_ALLOCATION: 'AccreditationVerifyAllocation',
    VIEW_ACCREDITATIONS: 'AccreditationViewAccreditations',
  }
};
